Evpn vxlan debug dump
dgsudharsan/sonic-utilities pull request #7
Opened 2021-08-31 20:05 UTC by dgsudharsan

#### What I did
Dump utility for EVPN and VxLAN

#### How I did it
Added changes implementing vxlan and evpn tables

#### How to verify it
Added UT to verify the changes.

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)
```
dump state vxlan_tunnel vtep_1336
{
    "vtep_1336": {
        "CONFIG_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL|vtep_1336": {
                        "src_ip": "10.1.0.32"
                    }
                }
            ],
            "tables_not_found": []
        },
        "APPL_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL_TABLE:vtep_1336": {
                        "src_ip": "10.1.0.32"
                    }
                }
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL:oid:0x2a00000000069f": {
                        "SAI_TUNNEL_ATTR_DECAP_MAPPERS": "2:oid:0x2900000000069b,oid:0x2900000000069d",
                        "SAI_TUNNEL_ATTR_ENCAP_MAPPERS": "2:oid:0x2900000000069c,oid:0x2900000000069e",
                        "SAI_TUNNEL_ATTR_ENCAP_SRC_IP": "10.1.0.32",
                        "SAI_TUNNEL_ATTR_PEER_MODE": "SAI_TUNNEL_PEER_MODE_P2MP",
                        "SAI_TUNNEL_ATTR_TYPE": "SAI_TUNNEL_TYPE_VXLAN",
                        "SAI_TUNNEL_ATTR_UNDERLAY_INTERFACE": "oid:0x600000000056a"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069c": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VLAN_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069e": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VIRTUAL_ROUTER_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069b": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069d": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VIRTUAL_ROUTER_ID"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY:oid:0x2b0000000006a0": {
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_ACTION_TUNNEL_ID": "oid:0x2a00000000069f",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_DST_IP": "10.1.0.32",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TUNNEL_TYPE": "SAI_TUNNEL_TYPE_VXLAN",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE": "SAI_TUNNEL_TERM_TABLE_ENTRY_TYPE_P2MP",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID": "oid:0x3000000000002"
                    }
                }
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0x2a00000000069f": "oid:0x2a",
                "oid:0x2900000000069c": "oid:0x100000029",
                "oid:0x2900000000069e": "oid:0x300000029",
                "oid:0x2900000000069b": "oid:0x29",
                "oid:0x2900000000069d": "oid:0x200000029",
                "oid:0x2b0000000006a0": "oid:0x420000002b"
            }
        },
        "STATE_DB": {
            "keys": [],
            "tables_not_found": [
                "VXLAN_TUNNEL_TABLE"
            ]
        }
    }
}
```
```
dump state vxlan_tunnel_map all
{
    "vtep_1336|map_1336_Vlan2345": {
        "CONFIG_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL_MAP|vtep_1336|map_1336_Vlan2345": {
                        "vlan": "Vlan2345",
                        "vni": "1336"
                    }
                }
            ],
            "tables_not_found": []
        },
        "APPL_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL_MAP_TABLE:vtep_1336:map_1336_Vlan2345": {
                        "vlan": "Vlan2345",
                        "vni": "1336"
                    }
                }
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP_ENTRY:oid:0x3b0000000006a1": {
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_TUNNEL_MAP": "oid:0x2900000000069b",
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_TUNNEL_MAP_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID",
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_VLAN_ID_VALUE": "2345",
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_VNI_ID_KEY": "1336"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069b": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID"
                    }
                }
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0x3b0000000006a1": "oid:0x10000003b",
                "oid:0x2900000000069b": "oid:0x29"
            }
        }
    }
}
```
```
dump state evpn 'Vlan2345:11.1.0.32'
{
    "Vlan2345:11.1.0.32": {
        "APPL_DB": {
            "keys": [
                {
                     "VXLAN_REMOTE_VNI_TABLE:Vlan2345:11.1.0.32": {
                         "vni": "1336"
                      }
                }
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                {
                        "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL:oid:0x2a0000000007e1": {
                             "SAI_TUNNEL_ATTR_UNDERLAY_INTERFACE": "oid:0x600000000056a",
                             "SAI_TUNNEL_ATTR_PEER_MODE": "SAI_TUNNEL_PEER_MODE_P2P",
                             "SAI_TUNNEL_ATTR_DECAP_MAPPERS": "2:oid:0x290000000007e9,oid:0x290000000007eb",
                             "SAI_TUNNEL_ATTR_ENCAP_SRC_IP": "10.1.0.32",
                             "SAI_TUNNEL_ATTR_ENCAP_DST_IP": "11.1.0.32",
                            "SAI_TUNNEL_ATTR_ENCAP_MAPPERS": "2:oid:0x290000000007ea,oid:0x290000000007ec",
                            "SAI_TUNNEL_ATTR_TYPE": "SAI_TUNNEL_TYPE_VXLAN"
                       },
                },
               {
                   "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY:oid:0x2b0000000007e1": {
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_ACTION_TUNNEL_ID": "oid:0x2a0000000007e1",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TUNNEL_TYPE": "SAI_TUNNEL_TYPE_VXLAN",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID": "oid:0x3000000000010",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_DST_IP": "10.1.0.32",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_SRC_IP": "11.1.0.32",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE": "SAI_TUNNEL_TERM_TABLE_ENTRY_TYPE_P2P"
                    }
                },
               {
                   "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007e9": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID"
                    }
                },
               {
                   "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007ec": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VIRTUAL_ROUTER_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007ea": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VLAN_ID_TO_VNI"
 [...]

2021-09-02 06:05 UTC, vivekreddynv commented on tests/dump_tests/module_tests/evpn_test.py
> +        ddiff = DeepDiff(sort_lists(returned), sort_lists(expect), ignore_order=True)
Can remove sort_lists, having ignore_order flag should work

2021-09-02 06:05 UTC, vivekreddynv commented on tests/dump_tests/module_tests/evpn_test.py
> +        ddiff = DeepDiff(sort_lists(returned), sort_lists(expect), ignore_order=True)
Can remove sort_lists, having ignore_order flag should work

2021-09-02 06:06 UTC, vivekreddynv commented on tests/dump_tests/module_tests/vxlan_tunnel_map_test.py
> +        ddiff = DeepDiff(sort_lists(returned), sort_lists(expect), ignore_order=True)
Can remove sort_lists, having ignore_order flag should work

2021-09-02 06:06 UTC, vivekreddynv commented on tests/dump_tests/module_tests/vxlan_tunnel_map_test.py
> +        ddiff = DeepDiff(sort_lists(returned), sort_lists(expect), ignore_order=True)
Can remove sort_lists, having ignore_order flag should work

2021-09-02 06:10 UTC, vivekreddynv commented on dump/plugins/evpn.py
> +        self.remote_vlan = evpn_name.split(':')[0]
Can have the lines 51 & 52 in the execute method itself

2021-09-02 06:26 UTC, vivekreddynv commented on dump/plugins/evpn.py
> +        print("state key " + state_key)
use verbose_print() instead

2021-09-02 06:31 UTC, vivekreddynv commented on dump/plugins/evpn.py
> +    ARG_NAME = "Remote VNI"
Does this have the scaling problem, which we've observed in the Route Module?

2021-09-02 06:43 UTC, vivekreddynv commented on dump/plugins/vxlan_tunnel.py
> +        ret["keys"] = [x for x in ret["keys"] if not self.dst_ip and ret["return_values"][x]["SAI_TUNNEL_ATTR_ENCAP_DST_IP"] == ""
Line seems large, i think it's better to split it.

2021-10-01 14:17 UTC, volodymyrsamotiy commented on dump/plugins/vxlan_tunnel.py
> +    Debug Dump Plugin for PORT Module
Looks there is typo, it is not PORT Module.

2021-10-01 14:17 UTC, volodymyrsamotiy commented on dump/plugins/vxlan_tunnel_map.py
> +    Debug Dump Plugin for PORT Module
Looks there is typo, it is not PORT Module.

2021-10-18 04:07 UTC, vivekreddynv requested changes

2021-10-18 04:07 UTC, vivekreddynv commented on dump/plugins/evpn.py
> +                               return_fields=["SAI_TUNNEL_ATTR_TYPE", "SAI_TUNNEL_ATTR_ENCAP_DST_IP",
`"SAI_TUNNEL_ATTR_ENCAP_DST_IP"` doesn't seem to used

2021-10-18 04:07 UTC, vivekreddynv commented on dump/plugins/evpn.py
> +                                  key_pattern = key, ns=self.ns)
Should be `key_pattern=key`

2021-10-18 04:07 UTC, vivekreddynv commented on dump/plugins/vxlan_tunnel.py
> +                              key_pattern = key, ns=self.ns)
Should be `key_pattern=key`

2021-10-18 04:07 UTC, vivekreddynv commented on dump/plugins/vxlan_tunnel.py
> +                              key_pattern = key, ns=self.ns)
Should be `key_pattern=key`

2021-10-18 04:07 UTC, vivekreddynv commented on dump/plugins/evpn.py
> +
Can remove this empty line

2021-10-19 16:24 UTC, vivekreddynv approved these changes

2021-10-21 14:45 UTC, volodymyrsamotiy approved these changes

2021-10-22 17:38 UTC, closed without merging